#spring.application.name=user
spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/user_db
#    username: ecom_job_app
#    password: Neel@007
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

