#spring.application.name=order
spring:
  application:
    name: order
  h2:
    console:
        enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql : true
    hibernate:
        dl-auto: create

server:
  port: 8084
